# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 10, 541, 491))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Tabs.setFont(font)
        self.Tabs.setStyleSheet("")
        self.Tabs.setObjectName("Tabs")
        self.Add = QtWidgets.QWidget()
        self.Add.setObjectName("Add")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Add)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Add_Worker = QtWidgets.QPushButton(self.Add)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Add_Worker.setFont(font)
        self.Add_Worker.setObjectName("Add_Worker")
        self.verticalLayout.addWidget(self.Add_Worker)
        self.line = QtWidgets.QFrame(self.Add)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Add_Visist = QtWidgets.QPushButton(self.Add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Add_Visist.setFont(font)
        self.Add_Visist.setObjectName("Add_Visist")
        self.verticalLayout.addWidget(self.Add_Visist)
        self.Tabs.addTab(self.Add, "")
        self.Base_Workers = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Base_Workers.setFont(font)
        self.Base_Workers.setObjectName("Base_Workers")
        self.Del_Button = QtWidgets.QPushButton(self.Base_Workers)
        self.Del_Button.setGeometry(QtCore.QRect(10, 60, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Del_Button.setFont(font)
        self.Del_Button.setObjectName("Del_Button")
        self.Edit_Button = QtWidgets.QPushButton(self.Base_Workers)
        self.Edit_Button.setGeometry(QtCore.QRect(280, 60, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Edit_Button.setFont(font)
        self.Edit_Button.setObjectName("Edit_Button")
        self.listWidget = QtWidgets.QListWidget(self.Base_Workers)
        self.listWidget.setGeometry(QtCore.QRect(0, 120, 501, 321))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.Base_Workers)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.Search_Button = QtWidgets.QPushButton(self.Base_Workers)
        self.Search_Button.setGeometry(QtCore.QRect(340, 10, 93, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Search_Button.setFont(font)
        self.Search_Button.setObjectName("Search_Button")
        self.line_2 = QtWidgets.QFrame(self.Base_Workers)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 491, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.Base_Workers)
        self.line_3.setGeometry(QtCore.QRect(7, 39, 491, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.Base_Workers)
        self.verticalScrollBar.setGeometry(QtCore.QRect(480, 120, 31, 321))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.Tabs.addTab(self.Base_Workers, "")
        self.Base_Visits = QtWidgets.QWidget()
        self.Base_Visits.setObjectName("Base_Visits")
        self.listWidget_2 = QtWidgets.QListWidget(self.Base_Visits)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 130, 481, 321))
        self.listWidget_2.setObjectName("listWidget_2")
        self.Edit_Button_2 = QtWidgets.QPushButton(self.Base_Visits)
        self.Edit_Button_2.setGeometry(QtCore.QRect(280, 70, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Edit_Button_2.setFont(font)
        self.Edit_Button_2.setObjectName("Edit_Button_2")
        self.line_4 = QtWidgets.QFrame(self.Base_Visits)
        self.line_4.setGeometry(QtCore.QRect(10, 110, 491, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Base_Visits)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 321, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.line_5 = QtWidgets.QFrame(self.Base_Visits)
        self.line_5.setGeometry(QtCore.QRect(7, 49, 491, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.Base_Visits)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(480, 130, 31, 321))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.Search_Button_2 = QtWidgets.QPushButton(self.Base_Visits)
        self.Search_Button_2.setGeometry(QtCore.QRect(340, 20, 93, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Search_Button_2.setFont(font)
        self.Search_Button_2.setObjectName("Search_Button_2")
        self.Del_Button_2 = QtWidgets.QPushButton(self.Base_Visits)
        self.Del_Button_2.setGeometry(QtCore.QRect(10, 70, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Del_Button_2.setFont(font)
        self.Del_Button_2.setObjectName("Del_Button_2")
        self.Tabs.addTab(self.Base_Visits, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add_Worker.setText(_translate("MainWindow", "Добавить Работника"))
        self.Add_Visist.setText(_translate("MainWindow", "Добавить посещение"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Add), _translate("MainWindow", "Добавление"))
        self.Del_Button.setText(_translate("MainWindow", "Удалить"))
        self.Edit_Button.setText(_translate("MainWindow", "Редактировать"))
        self.Search_Button.setText(_translate("MainWindow", "Поиск"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Base_Workers), _translate("MainWindow", "Работники"))
        self.Edit_Button_2.setText(_translate("MainWindow", "Редактировать"))
        self.Search_Button_2.setText(_translate("MainWindow", "Поиск"))
        self.Del_Button_2.setText(_translate("MainWindow", "Удалить"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Base_Visits), _translate("MainWindow", "Посещения"))
